version: "3.7"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
  coordinator:
    build:
      context: .
      args:
        - "coordinator"
    ports:
      - "8080:8080"
    environment:
      - NATS_URL=nats://nats:4222
      - PRETTY=true
      - DEBUG=true
    depends_on:
      - nats