// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: services/tasks/tasks.proto

package tasks

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId string `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_tasks_tasks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_tasks_tasks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_services_tasks_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *GetTasksRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

type GetTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Number   int32  `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Nreduce  int32  `protobuf:"varint,4,opt,name=nreduce,proto3" json:"nreduce,omitempty"`
	Type     string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	TaskType string `protobuf:"bytes,6,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
}

func (x *GetTasksResponse) Reset() {
	*x = GetTasksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_tasks_tasks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResponse) ProtoMessage() {}

func (x *GetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_tasks_tasks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResponse.ProtoReflect.Descriptor instead.
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return file_services_tasks_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *GetTasksResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTasksResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTasksResponse) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GetTasksResponse) GetNreduce() int32 {
	if x != nil {
		return x.Nreduce
	}
	return 0
}

func (x *GetTasksResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetTasksResponse) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type MarkTaskAsDoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskType string `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
}

func (x *MarkTaskAsDoneRequest) Reset() {
	*x = MarkTaskAsDoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_tasks_tasks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkTaskAsDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkTaskAsDoneRequest) ProtoMessage() {}

func (x *MarkTaskAsDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_tasks_tasks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkTaskAsDoneRequest.ProtoReflect.Descriptor instead.
func (*MarkTaskAsDoneRequest) Descriptor() ([]byte, []int) {
	return file_services_tasks_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *MarkTaskAsDoneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MarkTaskAsDoneRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type MarkTaskAsDoneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *MarkTaskAsDoneResponse) Reset() {
	*x = MarkTaskAsDoneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_tasks_tasks_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkTaskAsDoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkTaskAsDoneResponse) ProtoMessage() {}

func (x *MarkTaskAsDoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_tasks_tasks_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkTaskAsDoneResponse.ProtoReflect.Descriptor instead.
func (*MarkTaskAsDoneResponse) Descriptor() ([]byte, []int) {
	return file_services_tasks_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *MarkTaskAsDoneResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_services_tasks_tasks_proto protoreflect.FileDescriptor

var file_services_tasks_tasks_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73,
	0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x61,
	0x73, 0x6b, 0x73, 0x22, 0x2e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x49, 0x64, 0x22, 0x99, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x44, 0x0a, 0x15, 0x4d, 0x61, 0x72, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x73, 0x44, 0x6f, 0x6e,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x73,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x22, 0x30, 0x0a, 0x16, 0x4d, 0x61, 0x72, 0x6b, 0x54, 0x61, 0x73,
	0x6b, 0x41, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x97, 0x01, 0x0a, 0x05, 0x54, 0x61, 0x73, 0x6b,
	0x73, 0x12, 0x3d, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x16, 0x2e,
	0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4f, 0x0a, 0x0e, 0x4d, 0x61, 0x72, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x73, 0x44, 0x6f,
	0x6e, 0x65, 0x12, 0x1c, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x54,
	0x61, 0x73, 0x6b, 0x41, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x54, 0x61, 0x73,
	0x6b, 0x41, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x6c, 0x65, 0x78, 0x6f, 0x68, 0x6e, 0x65, 0x61, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x66, 0x6c,
	0x6f, 0x74, 0x74, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x74, 0x61,
	0x73, 0x6b, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_tasks_tasks_proto_rawDescOnce sync.Once
	file_services_tasks_tasks_proto_rawDescData = file_services_tasks_tasks_proto_rawDesc
)

func file_services_tasks_tasks_proto_rawDescGZIP() []byte {
	file_services_tasks_tasks_proto_rawDescOnce.Do(func() {
		file_services_tasks_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_tasks_tasks_proto_rawDescData)
	})
	return file_services_tasks_tasks_proto_rawDescData
}

var file_services_tasks_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_tasks_tasks_proto_goTypes = []interface{}{
	(*GetTasksRequest)(nil),        // 0: tasks.GetTasksRequest
	(*GetTasksResponse)(nil),       // 1: tasks.GetTasksResponse
	(*MarkTaskAsDoneRequest)(nil),  // 2: tasks.MarkTaskAsDoneRequest
	(*MarkTaskAsDoneResponse)(nil), // 3: tasks.MarkTaskAsDoneResponse
}
var file_services_tasks_tasks_proto_depIdxs = []int32{
	0, // 0: tasks.Tasks.GetTasks:input_type -> tasks.GetTasksRequest
	2, // 1: tasks.Tasks.MarkTaskAsDone:input_type -> tasks.MarkTaskAsDoneRequest
	1, // 2: tasks.Tasks.GetTasks:output_type -> tasks.GetTasksResponse
	3, // 3: tasks.Tasks.MarkTaskAsDone:output_type -> tasks.MarkTaskAsDoneResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_tasks_tasks_proto_init() }
func file_services_tasks_tasks_proto_init() {
	if File_services_tasks_tasks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_tasks_tasks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_tasks_tasks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTasksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_tasks_tasks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkTaskAsDoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_tasks_tasks_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkTaskAsDoneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_tasks_tasks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_tasks_tasks_proto_goTypes,
		DependencyIndexes: file_services_tasks_tasks_proto_depIdxs,
		MessageInfos:      file_services_tasks_tasks_proto_msgTypes,
	}.Build()
	File_services_tasks_tasks_proto = out.File
	file_services_tasks_tasks_proto_rawDesc = nil
	file_services_tasks_tasks_proto_goTypes = nil
	file_services_tasks_tasks_proto_depIdxs = nil
}
